### PR TITLE
Added RHEL to Teams

### PR DESCRIPTION
**Pull request by adamboutcher**
Added RHEL capability to MS teams/init.pp

### CODE REVIEW

**Comment by threepistons** [comment]
Thank you!

**Comment by threepistons** [comment]
@adamboutcher What RedHat OSes and versions are you using? So I can update the supported OS list in metadata.json.

**Comment by adamboutcher** [comment]
This works on Fedora 34 but should be from 32+ and CentOS/Rocky/Alma/RedHat 8.
Might work on CentOS7 but IIRC teams actually has a lib dependancy issue on C7.

**Comment by threepistons** [comment]
I'm not able to test on CentOS 7 (nor any of the other OSes you mention) because we only offer Debian-like OSes on the desktop, so I'll omit C7 sooner than claim to support something that might be broken and I can't verify.

**Pull request merged**
